# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.10'
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.4.2
    - name: Install dependencies
      run: poetry install --no-root
    - name: Lint with flake8, isort, black, and mypy
      run: |
        poetry run pflake8 .
        poetry run isort . --check-only
        poetry run black . --check
        poetry run mypy .
    - name: Test with unittest module
      run: |
        python3 test/test_main.py
